all:
	$(MAKE) -C case-studies/
	$(MAKE) -C conduit/
	$(MAKE) -C conclusion/
	$(MAKE) -C introduction/
	$(MAKE) -C measuring-cna/


clean:
	$(MAKE) clean -C case-studies/
	$(MAKE) clean -C conduit/
	$(MAKE) clean -C conclusion/
	$(MAKE) clean -C introduction/
	$(MAKE) clean -C measuring-cna/


cleaner:
	$(MAKE) cleaner -C case-studies/
	$(MAKE) cleaner -C conduit/
	$(MAKE) cleaner -C conclusion/
	$(MAKE) cleaner -C introduction/
	$(MAKE) cleaner -C measuring-cna/


fresh:
	$(MAKE) fresh -C case-studies/
	$(MAKE) fresh -C conduit/
	$(MAKE) fresh -C conclusion/
	$(MAKE) fresh -C introduction/
	$(MAKE) fresh -C measuring-cna/
