all:
	$(MAKE) -C case-studies/
	$(MAKE) -C conduit/
	$(MAKE) -C conclusion/
	$(MAKE) -C influencing-cna/
	$(MAKE) -C introduction/
	$(MAKE) -C measuring-cna/
	$(MAKE) -C sgp-lite/
	$(MAKE) -C tag-matching/


clean:
	$(MAKE) clean -C case-studies/
	$(MAKE) clean -C conduit/
	$(MAKE) clean -C conclusion/
	$(MAKE) clean -C influencing-cna/
	$(MAKE) clean -C introduction/
	$(MAKE) clean -C measuring-cna/
	$(MAKE) clean -C sgp-lite/
	$(MAKE) clean -C tag-matching/


cleaner:
	$(MAKE) cleaner -C case-studies/
	$(MAKE) cleaner -C conduit/
	$(MAKE) cleaner -C conclusion/
	$(MAKE) cleaner -C influencing-cna/
	$(MAKE) cleaner -C introduction/
	$(MAKE) cleaner -C measuring-cna/
	$(MAKE) cleaner -C sgp-lite/
	$(MAKE) cleaner -C tag-matching/


fresh:
	$(MAKE) fresh -C case-studies/
	$(MAKE) fresh -C conduit/
	$(MAKE) fresh -C conclusion/
	$(MAKE) fresh -C influencing-cna/
	$(MAKE) fresh -C introduction/
	$(MAKE) fresh -C measuring-cna/
	$(MAKE) fresh -C sgp-lite/
	$(MAKE) fresh -C tag-matching/
