all:
	$(MAKE) -C case-studies/
	$(MAKE) -C conclusion/
	$(MAKE) -C influencing-cna/
	$(MAKE) -C infrastructure/
	$(MAKE) -C introduction/
	$(MAKE) -C measuring-cna/

clean:
	$(MAKE) clean -C case-studies/
	$(MAKE) clean -C conclusion/
	$(MAKE) clean -C influencing-cna/
	$(MAKE) clean -C infrastructure/
	$(MAKE) clean -C introduction/
	$(MAKE) clean -C measuring-cna/

cleaner:
	$(MAKE) cleaner -C case-studies/
	$(MAKE) cleaner -C conclusion/
	$(MAKE) cleaner -C influencing-cna/
	$(MAKE) cleaner -C infrastructure/
	$(MAKE) cleaner -C introduction/
	$(MAKE) cleaner -C measuring-cna/

fresh:
	$(MAKE) fresh -C case-studies/
	$(MAKE) fresh -C conclusion/
	$(MAKE) fresh -C influencing-cna/
	$(MAKE) fresh -C infrastructure/
	$(MAKE) fresh -C introduction/
	$(MAKE) fresh -C measuring-cna/
