name: Build LaTeX document

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: '0 0 * * 0'

jobs:
  docker-build:
    name: Docker Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Push to DockerHub
        uses: docker/build-push-action@v1
        with:
          push: true
          tags: GITHUB_ACTION_${{ github.run_number }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: mmore500/dissertation
          add_git_labels: true

  build-draft:
    runs-on: ubuntu-20.04
    needs:
      - docker-build
    container:
      image: mmore500/dissertation:GITHUB_ACTION_${{ github.run_number }}
      # github actions requires root to access mounted volumes
      options: --cap-add=SYS_ADMIN
    steps:
      - run: make -C /opt/dissertation
      - name: Upload output as artifact
        uses: actions/upload-artifact@main
        with:
          name: manuscript
          path: /opt/dissertation/${{ github.event.repository.name }}-draft.pdf

  test-chapters:
    runs-on: ubuntu-20.04
    needs:
      - docker-build
    container:
      image: mmore500/dissertation:GITHUB_ACTION_${{ github.run_number }}
      # github actions requires root to access mounted volumes
      options: --cap-add=SYS_ADMIN
    steps:
      - run: make -C /opt/dissertation/ch
