name: Build LaTeX document

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build-latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
        with:
          submodules: 'recursive'
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          extra_system_packages: 'build-base'
          root_file: main.tex
          post_compile: 'make'
      - run: mkdir deploy
      - run: cp workspace-draft.pdf deploy/${{ github.event.repository.name }}-draft.pdf
      - name: Upload output as artifact
        uses: actions/upload-artifact@main
        with:
          name: manuscript
          path: deploy/${{ github.event.repository.name }}-draft.pdf
