name: Enforce Tidyness

on:
  push:
    branches:
      - master

jobs:
  enforce-tidyness:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - run: ./ci/test_tidy.sh
